# Generated by Django 3.0.4 on 2020-03-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0004_auto_20200331_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinlog',
            name='checked_in_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
