# Generated by Django 3.0.4 on 2020-03-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
