# Generated by Django 3.0.4 on 2020-03-31 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0007_membership_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='membership_management.Membership'),
        ),
    ]
