# Generated by Django 3.0.4 on 2020-04-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0008_auto_20200331_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_recurring',
            field=models.CharField(choices=[('M', 'Monthly'), ('W', 'Weekly'), ('Y', 'Yearly'), ('N', 'Not Recurring')], default='N', max_length=1),
        ),
    ]
