# Generated by Django 3.0.4 on 2020-04-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0009_auto_20200402_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='recurring_cycle_starts_on',
            field=models.DateField(null=True, verbose_name='recurring cycle start date (ONLY for recurring memberships)'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_recurring',
            field=models.CharField(choices=[('M', 'Every Month'), ('W', 'Every Week'), ('Y', 'Every Year'), ('2', 'Every 2 Weeks'), ('N', 'Not Recurring')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='membership',
            name='number_of_days_valid',
            field=models.IntegerField(default=0, verbose_name='number of days valid (ONLY for non recurring memberships)'),
        ),
    ]
