# Generated by Django 3.0.4 on 2020-04-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0011_membership_banner_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='recurring_cycle_starts_on',
        ),
        migrations.AddField(
            model_name='member',
            name='override_recurring_cycle_starts_on',
            field=models.DateField(blank=True, null=True, verbose_name='recurring cycle start date (ONLY for recurring memberships)'),
        ),
    ]
