# Generated by Django 3.0.4 on 2020-04-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0012_auto_20200402_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='display_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
