# Generated by Django 3.0.4 on 2020-04-04 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0014_auto_20200402_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paid_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='credit_card_last4',
        ),
        migrations.AddField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='membership_management.Membership'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_processor_id',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='override_recurring_cycle_starts_on',
            field=models.DateField(blank=True, null=True, verbose_name='Override recurring cycle start date (ONLY for recurring memberships)'),
        ),
    ]
