# Generated by Django 3.0.4 on 2020-04-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0016_auto_20200404_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='is_recurring',
        ),
        migrations.AddField(
            model_name='membership',
            name='subscription_plan_id',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='subscription plan ID in Stripe dashboard'),
        ),
    ]
