# Generated by Django 3.0.4 on 2020-04-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0017_auto_20200404_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_subscription',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='number_of_days_valid',
            field=models.IntegerField(default=0, verbose_name='[ONLY for ONE-TIME memberships] number of days valid'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='subscription_plan_id',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='[ONLY for SUBSCRIPTIONS] plan ID in Stripe dashboard'),
        ),
    ]
