# Generated by Django 3.0.4 on 2020-04-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0018_auto_20200404_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
