# Generated by Django 3.0.4 on 2020-04-11 00:00

from django.db import migrations, models
import hotshot_web.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0022_auto_20200410_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, storage=hotshot_web.storage_backends.PrivateMediaStorage(), upload_to='profile_pic'),
        ),
    ]
