# Generated by Django 3.0.4 on 2020-04-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0025_auto_20200412_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinlog',
            name='member',
        ),
        migrations.AddField(
            model_name='checkinlog',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email address'),
        ),
        migrations.AddField(
            model_name='checkinlog',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkinlog',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkinlog',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
