# Generated by Django 3.0.5 on 2020-04-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0026_auto_20200412_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='[DO NOT EDIT UNLESS INSTRUCTED] Stripe customer ID'),
        ),
    ]
