# Generated by Django 3.0.5 on 2020-04-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0027_auto_20200414_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxiliarymember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_displayed',
            field=models.BooleanField(default=True, verbose_name='Is displayed for purchase'),
        ),
    ]
