# Generated by Django 3.0.5 on 2020-05-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0028_auto_20200414_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='tax_rate_id',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='[ONLY for SUBSCRIPTIONS] tax rate ID in Stripe dashboard'),
        ),
    ]
