# Generated by Django 3.0.5 on 2020-05-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0029_membership_tax_rate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='tax_rate_id',
        ),
    ]
