# Generated by Django 3.0.5 on 2020-07-26 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0030_remove_membership_tax_rate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinlog',
            name='checked_in_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='membership',
            name='subscription_plan_id',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='[ONLY for SUBSCRIPTIONS] price ID in Stripe dashboard'),
        ),
    ]
